# kubernetes service for the crowdsense application

apiVersion: v1
kind: Service
metadata:
  name: crowdsense-server
  labels:
    app: crowdsense
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: crowdsense
